# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dmSettings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dmSettings.proto',
  package='dm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64mSettings.proto\x12\x02\x64m\"\x94\x01\n\x0e\x44mWebViewReply\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08textSide\x18\x03 \x01(\t\x12\x1e\n\x05\x64mSge\x18\x04 \x01(\x0b\x32\x0f.dm.DmSegConfig\x12\x12\n\nspecialDms\x18\x06 \x03(\t\x12\x10\n\x08\x63heckBox\x18\x07 \x01(\x08\x12\r\n\x05\x63ount\x18\x08 \x01(\x03\".\n\x0b\x44mSegConfig\x12\x10\n\x08pageSize\x18\x01 \x01(\x03\x12\r\n\x05total\x18\x02 \x01(\x03\x62\x06proto3'
)




_DMWEBVIEWREPLY = _descriptor.Descriptor(
  name='DmWebViewReply',
  full_name='dm.DmWebViewReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='dm.DmWebViewReply.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='dm.DmWebViewReply.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='textSide', full_name='dm.DmWebViewReply.textSide', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dmSge', full_name='dm.DmWebViewReply.dmSge', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='specialDms', full_name='dm.DmWebViewReply.specialDms', index=4,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='checkBox', full_name='dm.DmWebViewReply.checkBox', index=5,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='dm.DmWebViewReply.count', index=6,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=173,
)


_DMSEGCONFIG = _descriptor.Descriptor(
  name='DmSegConfig',
  full_name='dm.DmSegConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='dm.DmSegConfig.pageSize', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='dm.DmSegConfig.total', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=221,
)

_DMWEBVIEWREPLY.fields_by_name['dmSge'].message_type = _DMSEGCONFIG
DESCRIPTOR.message_types_by_name['DmWebViewReply'] = _DMWEBVIEWREPLY
DESCRIPTOR.message_types_by_name['DmSegConfig'] = _DMSEGCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DmWebViewReply = _reflection.GeneratedProtocolMessageType('DmWebViewReply', (_message.Message,), {
  'DESCRIPTOR' : _DMWEBVIEWREPLY,
  '__module__' : 'dmSettings_pb2'
  # @@protoc_insertion_point(class_scope:dm.DmWebViewReply)
  })
_sym_db.RegisterMessage(DmWebViewReply)

DmSegConfig = _reflection.GeneratedProtocolMessageType('DmSegConfig', (_message.Message,), {
  'DESCRIPTOR' : _DMSEGCONFIG,
  '__module__' : 'dmSettings_pb2'
  # @@protoc_insertion_point(class_scope:dm.DmSegConfig)
  })
_sym_db.RegisterMessage(DmSegConfig)


# @@protoc_insertion_point(module_scope)
